language: node_js
node_js:
  - "5"

cache:
  directories:
    - node_modules

install:
  - npm install --dev
  - gem install sass

script:
  - npm test
  - sass -Istyles styles/_coop-toolkit.scss > /dev/null
