language: node_js
node_js:
  - "5"

cache:
  directories:
    - node_modules

install:
  - npm install --dev
  - npm install node-sass -g
  - gem install sass

script:
  - npm test
  - node-sass --include-path styles styles/_coop-toolkit.scss > /dev/null
  - sass styles/_coop-toolkit.scss > /dev/null
